package com.nf147.ssm.dao;

import com.nf147.ssm.entity.Distribution;
import java.util.List;

public interface DistributionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribution
     *
     * @mbg.generated
     */
    int insert(Distribution record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribution
     *
     * @mbg.generated
     */
    List<Distribution> selectAll();
}