package com.nf147.ssm.dao;

import com.nf147.ssm.entity.Vehicle;
import java.util.List;

public interface VehicleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle
     *
     * @mbg.generated
     */
    int insert(Vehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle
     *
     * @mbg.generated
     */
    List<Vehicle> selectAll();
}