package com.nf147.ssm.entity;

import java.util.Date;

public class Customer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customer_id
     *
     * @mbg.generated
     */
    private String customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customer_name
     *
     * @mbg.generated
     */
    private String customerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customer_sex
     *
     * @mbg.generated
     */
    private Integer customerSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customer_pwd
     *
     * @mbg.generated
     */
    private String customerPwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customer_phone
     *
     * @mbg.generated
     */
    private String customerPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customer_birthday
     *
     * @mbg.generated
     */
    private Date customerBirthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customer_address
     *
     * @mbg.generated
     */
    private String customerAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customer_remarks
     *
     * @mbg.generated
     */
    private String customerRemarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.customer_id
     *
     * @return the value of customer.customer_id
     *
     * @mbg.generated
     */
    public String getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.customer_id
     *
     * @param customerId the value for customer.customer_id
     *
     * @mbg.generated
     */
    public void setCustomerId(String customerId) {
        this.customerId = customerId == null ? null : customerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.customer_name
     *
     * @return the value of customer.customer_name
     *
     * @mbg.generated
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.customer_name
     *
     * @param customerName the value for customer.customer_name
     *
     * @mbg.generated
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName == null ? null : customerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.customer_sex
     *
     * @return the value of customer.customer_sex
     *
     * @mbg.generated
     */
    public Integer getCustomerSex() {
        return customerSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.customer_sex
     *
     * @param customerSex the value for customer.customer_sex
     *
     * @mbg.generated
     */
    public void setCustomerSex(Integer customerSex) {
        this.customerSex = customerSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.user_id
     *
     * @return the value of customer.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.user_id
     *
     * @param userId the value for customer.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.customer_pwd
     *
     * @return the value of customer.customer_pwd
     *
     * @mbg.generated
     */
    public String getCustomerPwd() {
        return customerPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.customer_pwd
     *
     * @param customerPwd the value for customer.customer_pwd
     *
     * @mbg.generated
     */
    public void setCustomerPwd(String customerPwd) {
        this.customerPwd = customerPwd == null ? null : customerPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.customer_phone
     *
     * @return the value of customer.customer_phone
     *
     * @mbg.generated
     */
    public String getCustomerPhone() {
        return customerPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.customer_phone
     *
     * @param customerPhone the value for customer.customer_phone
     *
     * @mbg.generated
     */
    public void setCustomerPhone(String customerPhone) {
        this.customerPhone = customerPhone == null ? null : customerPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.customer_birthday
     *
     * @return the value of customer.customer_birthday
     *
     * @mbg.generated
     */
    public Date getCustomerBirthday() {
        return customerBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.customer_birthday
     *
     * @param customerBirthday the value for customer.customer_birthday
     *
     * @mbg.generated
     */
    public void setCustomerBirthday(Date customerBirthday) {
        this.customerBirthday = customerBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.customer_address
     *
     * @return the value of customer.customer_address
     *
     * @mbg.generated
     */
    public String getCustomerAddress() {
        return customerAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.customer_address
     *
     * @param customerAddress the value for customer.customer_address
     *
     * @mbg.generated
     */
    public void setCustomerAddress(String customerAddress) {
        this.customerAddress = customerAddress == null ? null : customerAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.customer_remarks
     *
     * @return the value of customer.customer_remarks
     *
     * @mbg.generated
     */
    public String getCustomerRemarks() {
        return customerRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.customer_remarks
     *
     * @param customerRemarks the value for customer.customer_remarks
     *
     * @mbg.generated
     */
    public void setCustomerRemarks(String customerRemarks) {
        this.customerRemarks = customerRemarks == null ? null : customerRemarks.trim();
    }
}