package com.nf147.ssm.entity;

public class Distribution {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distribution.distribution_id
     *
     * @mbg.generated
     */
    private String distributionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distribution.distribution_name
     *
     * @mbg.generated
     */
    private String distributionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distribution.province_id
     *
     * @mbg.generated
     */
    private String provinceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distribution.city_id
     *
     * @mbg.generated
     */
    private String cityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distribution.admin_id
     *
     * @mbg.generated
     */
    private String adminId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distribution.distribution_phone
     *
     * @mbg.generated
     */
    private String distributionPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distribution.distribution_address
     *
     * @mbg.generated
     */
    private String distributionAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distribution.distribution_remarks
     *
     * @mbg.generated
     */
    private String distributionRemarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distribution.distribution_id
     *
     * @return the value of distribution.distribution_id
     *
     * @mbg.generated
     */
    public String getDistributionId() {
        return distributionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distribution.distribution_id
     *
     * @param distributionId the value for distribution.distribution_id
     *
     * @mbg.generated
     */
    public void setDistributionId(String distributionId) {
        this.distributionId = distributionId == null ? null : distributionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distribution.distribution_name
     *
     * @return the value of distribution.distribution_name
     *
     * @mbg.generated
     */
    public String getDistributionName() {
        return distributionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distribution.distribution_name
     *
     * @param distributionName the value for distribution.distribution_name
     *
     * @mbg.generated
     */
    public void setDistributionName(String distributionName) {
        this.distributionName = distributionName == null ? null : distributionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distribution.province_id
     *
     * @return the value of distribution.province_id
     *
     * @mbg.generated
     */
    public String getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distribution.province_id
     *
     * @param provinceId the value for distribution.province_id
     *
     * @mbg.generated
     */
    public void setProvinceId(String provinceId) {
        this.provinceId = provinceId == null ? null : provinceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distribution.city_id
     *
     * @return the value of distribution.city_id
     *
     * @mbg.generated
     */
    public String getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distribution.city_id
     *
     * @param cityId the value for distribution.city_id
     *
     * @mbg.generated
     */
    public void setCityId(String cityId) {
        this.cityId = cityId == null ? null : cityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distribution.admin_id
     *
     * @return the value of distribution.admin_id
     *
     * @mbg.generated
     */
    public String getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distribution.admin_id
     *
     * @param adminId the value for distribution.admin_id
     *
     * @mbg.generated
     */
    public void setAdminId(String adminId) {
        this.adminId = adminId == null ? null : adminId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distribution.distribution_phone
     *
     * @return the value of distribution.distribution_phone
     *
     * @mbg.generated
     */
    public String getDistributionPhone() {
        return distributionPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distribution.distribution_phone
     *
     * @param distributionPhone the value for distribution.distribution_phone
     *
     * @mbg.generated
     */
    public void setDistributionPhone(String distributionPhone) {
        this.distributionPhone = distributionPhone == null ? null : distributionPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distribution.distribution_address
     *
     * @return the value of distribution.distribution_address
     *
     * @mbg.generated
     */
    public String getDistributionAddress() {
        return distributionAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distribution.distribution_address
     *
     * @param distributionAddress the value for distribution.distribution_address
     *
     * @mbg.generated
     */
    public void setDistributionAddress(String distributionAddress) {
        this.distributionAddress = distributionAddress == null ? null : distributionAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distribution.distribution_remarks
     *
     * @return the value of distribution.distribution_remarks
     *
     * @mbg.generated
     */
    public String getDistributionRemarks() {
        return distributionRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distribution.distribution_remarks
     *
     * @param distributionRemarks the value for distribution.distribution_remarks
     *
     * @mbg.generated
     */
    public void setDistributionRemarks(String distributionRemarks) {
        this.distributionRemarks = distributionRemarks == null ? null : distributionRemarks.trim();
    }
}