package com.nf147.ssm.entity;

import java.util.Date;

public class Handover {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column handover.start_city
     *
     * @mbg.generated
     */
    private String startCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column handover.end_city
     *
     * @mbg.generated
     */
    private String endCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column handover.arrived_city
     *
     * @mbg.generated
     */
    private String arrivedCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column handover.handover_type
     *
     * @mbg.generated
     */
    private Integer handoverType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column handover.generation_time
     *
     * @mbg.generated
     */
    private Date generationTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column handover.handover_remarks
     *
     * @mbg.generated
     */
    private String handoverRemarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column handover.start_city
     *
     * @return the value of handover.start_city
     *
     * @mbg.generated
     */
    public String getStartCity() {
        return startCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column handover.start_city
     *
     * @param startCity the value for handover.start_city
     *
     * @mbg.generated
     */
    public void setStartCity(String startCity) {
        this.startCity = startCity == null ? null : startCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column handover.end_city
     *
     * @return the value of handover.end_city
     *
     * @mbg.generated
     */
    public String getEndCity() {
        return endCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column handover.end_city
     *
     * @param endCity the value for handover.end_city
     *
     * @mbg.generated
     */
    public void setEndCity(String endCity) {
        this.endCity = endCity == null ? null : endCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column handover.arrived_city
     *
     * @return the value of handover.arrived_city
     *
     * @mbg.generated
     */
    public String getArrivedCity() {
        return arrivedCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column handover.arrived_city
     *
     * @param arrivedCity the value for handover.arrived_city
     *
     * @mbg.generated
     */
    public void setArrivedCity(String arrivedCity) {
        this.arrivedCity = arrivedCity == null ? null : arrivedCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column handover.handover_type
     *
     * @return the value of handover.handover_type
     *
     * @mbg.generated
     */
    public Integer getHandoverType() {
        return handoverType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column handover.handover_type
     *
     * @param handoverType the value for handover.handover_type
     *
     * @mbg.generated
     */
    public void setHandoverType(Integer handoverType) {
        this.handoverType = handoverType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column handover.generation_time
     *
     * @return the value of handover.generation_time
     *
     * @mbg.generated
     */
    public Date getGenerationTime() {
        return generationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column handover.generation_time
     *
     * @param generationTime the value for handover.generation_time
     *
     * @mbg.generated
     */
    public void setGenerationTime(Date generationTime) {
        this.generationTime = generationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column handover.handover_remarks
     *
     * @return the value of handover.handover_remarks
     *
     * @mbg.generated
     */
    public String getHandoverRemarks() {
        return handoverRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column handover.handover_remarks
     *
     * @param handoverRemarks the value for handover.handover_remarks
     *
     * @mbg.generated
     */
    public void setHandoverRemarks(String handoverRemarks) {
        this.handoverRemarks = handoverRemarks == null ? null : handoverRemarks.trim();
    }
}