package com.nf147.ssm.entity;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_id
     *
     * @mbg.generated
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_type
     *
     * @mbg.generated
     */
    private Integer orderType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_number
     *
     * @mbg.generated
     */
    private String orderNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.goods_name
     *
     * @mbg.generated
     */
    private String goodsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.goods_weight
     *
     * @mbg.generated
     */
    private Integer goodsWeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.mailer_name
     *
     * @mbg.generated
     */
    private String mailerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.mailer_address
     *
     * @mbg.generated
     */
    private String mailerAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.mailer_phone
     *
     * @mbg.generated
     */
    private String mailerPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.receiver_name
     *
     * @mbg.generated
     */
    private String receiverName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.receiver_type
     *
     * @mbg.generated
     */
    private Integer receiverType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.receiver_address
     *
     * @mbg.generated
     */
    private String receiverAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.receiver_phone
     *
     * @mbg.generated
     */
    private String receiverPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.start_city
     *
     * @mbg.generated
     */
    private String startCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.middle_city
     *
     * @mbg.generated
     */
    private String middleCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.end_city
     *
     * @mbg.generated
     */
    private String endCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.transport_price
     *
     * @mbg.generated
     */
    private Long transportPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.distribution_price
     *
     * @mbg.generated
     */
    private Long distributionPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.carriage_price
     *
     * @mbg.generated
     */
    private Long carriagePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.total_price
     *
     * @mbg.generated
     */
    private String totalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.vehicle_id
     *
     * @mbg.generated
     */
    private String vehicleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_remarks
     *
     * @mbg.generated
     */
    private String orderRemarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_id
     *
     * @return the value of order.order_id
     *
     * @mbg.generated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_id
     *
     * @param orderId the value for order.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_type
     *
     * @return the value of order.order_type
     *
     * @mbg.generated
     */
    public Integer getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_type
     *
     * @param orderType the value for order.order_type
     *
     * @mbg.generated
     */
    public void setOrderType(Integer orderType) {
        this.orderType = orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_number
     *
     * @return the value of order.order_number
     *
     * @mbg.generated
     */
    public String getOrderNumber() {
        return orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_number
     *
     * @param orderNumber the value for order.order_number
     *
     * @mbg.generated
     */
    public void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber == null ? null : orderNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.goods_name
     *
     * @return the value of order.goods_name
     *
     * @mbg.generated
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.goods_name
     *
     * @param goodsName the value for order.goods_name
     *
     * @mbg.generated
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.goods_weight
     *
     * @return the value of order.goods_weight
     *
     * @mbg.generated
     */
    public Integer getGoodsWeight() {
        return goodsWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.goods_weight
     *
     * @param goodsWeight the value for order.goods_weight
     *
     * @mbg.generated
     */
    public void setGoodsWeight(Integer goodsWeight) {
        this.goodsWeight = goodsWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.mailer_name
     *
     * @return the value of order.mailer_name
     *
     * @mbg.generated
     */
    public String getMailerName() {
        return mailerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.mailer_name
     *
     * @param mailerName the value for order.mailer_name
     *
     * @mbg.generated
     */
    public void setMailerName(String mailerName) {
        this.mailerName = mailerName == null ? null : mailerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.mailer_address
     *
     * @return the value of order.mailer_address
     *
     * @mbg.generated
     */
    public String getMailerAddress() {
        return mailerAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.mailer_address
     *
     * @param mailerAddress the value for order.mailer_address
     *
     * @mbg.generated
     */
    public void setMailerAddress(String mailerAddress) {
        this.mailerAddress = mailerAddress == null ? null : mailerAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.mailer_phone
     *
     * @return the value of order.mailer_phone
     *
     * @mbg.generated
     */
    public String getMailerPhone() {
        return mailerPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.mailer_phone
     *
     * @param mailerPhone the value for order.mailer_phone
     *
     * @mbg.generated
     */
    public void setMailerPhone(String mailerPhone) {
        this.mailerPhone = mailerPhone == null ? null : mailerPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.receiver_name
     *
     * @return the value of order.receiver_name
     *
     * @mbg.generated
     */
    public String getReceiverName() {
        return receiverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.receiver_name
     *
     * @param receiverName the value for order.receiver_name
     *
     * @mbg.generated
     */
    public void setReceiverName(String receiverName) {
        this.receiverName = receiverName == null ? null : receiverName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.receiver_type
     *
     * @return the value of order.receiver_type
     *
     * @mbg.generated
     */
    public Integer getReceiverType() {
        return receiverType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.receiver_type
     *
     * @param receiverType the value for order.receiver_type
     *
     * @mbg.generated
     */
    public void setReceiverType(Integer receiverType) {
        this.receiverType = receiverType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.receiver_address
     *
     * @return the value of order.receiver_address
     *
     * @mbg.generated
     */
    public String getReceiverAddress() {
        return receiverAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.receiver_address
     *
     * @param receiverAddress the value for order.receiver_address
     *
     * @mbg.generated
     */
    public void setReceiverAddress(String receiverAddress) {
        this.receiverAddress = receiverAddress == null ? null : receiverAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.receiver_phone
     *
     * @return the value of order.receiver_phone
     *
     * @mbg.generated
     */
    public String getReceiverPhone() {
        return receiverPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.receiver_phone
     *
     * @param receiverPhone the value for order.receiver_phone
     *
     * @mbg.generated
     */
    public void setReceiverPhone(String receiverPhone) {
        this.receiverPhone = receiverPhone == null ? null : receiverPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.start_city
     *
     * @return the value of order.start_city
     *
     * @mbg.generated
     */
    public String getStartCity() {
        return startCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.start_city
     *
     * @param startCity the value for order.start_city
     *
     * @mbg.generated
     */
    public void setStartCity(String startCity) {
        this.startCity = startCity == null ? null : startCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.middle_city
     *
     * @return the value of order.middle_city
     *
     * @mbg.generated
     */
    public String getMiddleCity() {
        return middleCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.middle_city
     *
     * @param middleCity the value for order.middle_city
     *
     * @mbg.generated
     */
    public void setMiddleCity(String middleCity) {
        this.middleCity = middleCity == null ? null : middleCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.end_city
     *
     * @return the value of order.end_city
     *
     * @mbg.generated
     */
    public String getEndCity() {
        return endCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.end_city
     *
     * @param endCity the value for order.end_city
     *
     * @mbg.generated
     */
    public void setEndCity(String endCity) {
        this.endCity = endCity == null ? null : endCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.transport_price
     *
     * @return the value of order.transport_price
     *
     * @mbg.generated
     */
    public Long getTransportPrice() {
        return transportPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.transport_price
     *
     * @param transportPrice the value for order.transport_price
     *
     * @mbg.generated
     */
    public void setTransportPrice(Long transportPrice) {
        this.transportPrice = transportPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.distribution_price
     *
     * @return the value of order.distribution_price
     *
     * @mbg.generated
     */
    public Long getDistributionPrice() {
        return distributionPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.distribution_price
     *
     * @param distributionPrice the value for order.distribution_price
     *
     * @mbg.generated
     */
    public void setDistributionPrice(Long distributionPrice) {
        this.distributionPrice = distributionPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.carriage_price
     *
     * @return the value of order.carriage_price
     *
     * @mbg.generated
     */
    public Long getCarriagePrice() {
        return carriagePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.carriage_price
     *
     * @param carriagePrice the value for order.carriage_price
     *
     * @mbg.generated
     */
    public void setCarriagePrice(Long carriagePrice) {
        this.carriagePrice = carriagePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.total_price
     *
     * @return the value of order.total_price
     *
     * @mbg.generated
     */
    public String getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.total_price
     *
     * @param totalPrice the value for order.total_price
     *
     * @mbg.generated
     */
    public void setTotalPrice(String totalPrice) {
        this.totalPrice = totalPrice == null ? null : totalPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.vehicle_id
     *
     * @return the value of order.vehicle_id
     *
     * @mbg.generated
     */
    public String getVehicleId() {
        return vehicleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.vehicle_id
     *
     * @param vehicleId the value for order.vehicle_id
     *
     * @mbg.generated
     */
    public void setVehicleId(String vehicleId) {
        this.vehicleId = vehicleId == null ? null : vehicleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_remarks
     *
     * @return the value of order.order_remarks
     *
     * @mbg.generated
     */
    public String getOrderRemarks() {
        return orderRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_remarks
     *
     * @param orderRemarks the value for order.order_remarks
     *
     * @mbg.generated
     */
    public void setOrderRemarks(String orderRemarks) {
        this.orderRemarks = orderRemarks == null ? null : orderRemarks.trim();
    }
}