package com.nf147.ssm.entity;

public class Range {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column range.range_id
     *
     * @mbg.generated
     */
    private Integer rangeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column range.range_name
     *
     * @mbg.generated
     */
    private String rangeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column range.range_price
     *
     * @mbg.generated
     */
    private Long rangePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column range.city_id
     *
     * @mbg.generated
     */
    private String cityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column range.range_remarks
     *
     * @mbg.generated
     */
    private String rangeRemarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column range.range_id
     *
     * @return the value of range.range_id
     *
     * @mbg.generated
     */
    public Integer getRangeId() {
        return rangeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column range.range_id
     *
     * @param rangeId the value for range.range_id
     *
     * @mbg.generated
     */
    public void setRangeId(Integer rangeId) {
        this.rangeId = rangeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column range.range_name
     *
     * @return the value of range.range_name
     *
     * @mbg.generated
     */
    public String getRangeName() {
        return rangeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column range.range_name
     *
     * @param rangeName the value for range.range_name
     *
     * @mbg.generated
     */
    public void setRangeName(String rangeName) {
        this.rangeName = rangeName == null ? null : rangeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column range.range_price
     *
     * @return the value of range.range_price
     *
     * @mbg.generated
     */
    public Long getRangePrice() {
        return rangePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column range.range_price
     *
     * @param rangePrice the value for range.range_price
     *
     * @mbg.generated
     */
    public void setRangePrice(Long rangePrice) {
        this.rangePrice = rangePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column range.city_id
     *
     * @return the value of range.city_id
     *
     * @mbg.generated
     */
    public String getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column range.city_id
     *
     * @param cityId the value for range.city_id
     *
     * @mbg.generated
     */
    public void setCityId(String cityId) {
        this.cityId = cityId == null ? null : cityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column range.range_remarks
     *
     * @return the value of range.range_remarks
     *
     * @mbg.generated
     */
    public String getRangeRemarks() {
        return rangeRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column range.range_remarks
     *
     * @param rangeRemarks the value for range.range_remarks
     *
     * @mbg.generated
     */
    public void setRangeRemarks(String rangeRemarks) {
        this.rangeRemarks = rangeRemarks == null ? null : rangeRemarks.trim();
    }
}