package com.nf147.ssm.entity;

public class Route {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.route_id
     *
     * @mbg.generated
     */
    private String routeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.route_name
     *
     * @mbg.generated
     */
    private String routeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.start_province
     *
     * @mbg.generated
     */
    private String startProvince;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.start_city
     *
     * @mbg.generated
     */
    private String startCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.middle_province
     *
     * @mbg.generated
     */
    private String middleProvince;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.middle_city
     *
     * @mbg.generated
     */
    private String middleCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.end_province
     *
     * @mbg.generated
     */
    private String endProvince;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.end__city
     *
     * @mbg.generated
     */
    private String endCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.carriage_price
     *
     * @mbg.generated
     */
    private Long carriagePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.route_remarks
     *
     * @mbg.generated
     */
    private String routeRemarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.route_id
     *
     * @return the value of route.route_id
     *
     * @mbg.generated
     */
    public String getRouteId() {
        return routeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.route_id
     *
     * @param routeId the value for route.route_id
     *
     * @mbg.generated
     */
    public void setRouteId(String routeId) {
        this.routeId = routeId == null ? null : routeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.route_name
     *
     * @return the value of route.route_name
     *
     * @mbg.generated
     */
    public String getRouteName() {
        return routeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.route_name
     *
     * @param routeName the value for route.route_name
     *
     * @mbg.generated
     */
    public void setRouteName(String routeName) {
        this.routeName = routeName == null ? null : routeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.start_province
     *
     * @return the value of route.start_province
     *
     * @mbg.generated
     */
    public String getStartProvince() {
        return startProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.start_province
     *
     * @param startProvince the value for route.start_province
     *
     * @mbg.generated
     */
    public void setStartProvince(String startProvince) {
        this.startProvince = startProvince == null ? null : startProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.start_city
     *
     * @return the value of route.start_city
     *
     * @mbg.generated
     */
    public String getStartCity() {
        return startCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.start_city
     *
     * @param startCity the value for route.start_city
     *
     * @mbg.generated
     */
    public void setStartCity(String startCity) {
        this.startCity = startCity == null ? null : startCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.middle_province
     *
     * @return the value of route.middle_province
     *
     * @mbg.generated
     */
    public String getMiddleProvince() {
        return middleProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.middle_province
     *
     * @param middleProvince the value for route.middle_province
     *
     * @mbg.generated
     */
    public void setMiddleProvince(String middleProvince) {
        this.middleProvince = middleProvince == null ? null : middleProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.middle_city
     *
     * @return the value of route.middle_city
     *
     * @mbg.generated
     */
    public String getMiddleCity() {
        return middleCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.middle_city
     *
     * @param middleCity the value for route.middle_city
     *
     * @mbg.generated
     */
    public void setMiddleCity(String middleCity) {
        this.middleCity = middleCity == null ? null : middleCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.end_province
     *
     * @return the value of route.end_province
     *
     * @mbg.generated
     */
    public String getEndProvince() {
        return endProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.end_province
     *
     * @param endProvince the value for route.end_province
     *
     * @mbg.generated
     */
    public void setEndProvince(String endProvince) {
        this.endProvince = endProvince == null ? null : endProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.end__city
     *
     * @return the value of route.end__city
     *
     * @mbg.generated
     */
    public String getEndCity() {
        return endCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.end__city
     *
     * @param endCity the value for route.end__city
     *
     * @mbg.generated
     */
    public void setEndCity(String endCity) {
        this.endCity = endCity == null ? null : endCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.carriage_price
     *
     * @return the value of route.carriage_price
     *
     * @mbg.generated
     */
    public Long getCarriagePrice() {
        return carriagePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.carriage_price
     *
     * @param carriagePrice the value for route.carriage_price
     *
     * @mbg.generated
     */
    public void setCarriagePrice(Long carriagePrice) {
        this.carriagePrice = carriagePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.route_remarks
     *
     * @return the value of route.route_remarks
     *
     * @mbg.generated
     */
    public String getRouteRemarks() {
        return routeRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.route_remarks
     *
     * @param routeRemarks the value for route.route_remarks
     *
     * @mbg.generated
     */
    public void setRouteRemarks(String routeRemarks) {
        this.routeRemarks = routeRemarks == null ? null : routeRemarks.trim();
    }
}