package com.nf147.ssm.entity;

import java.util.Date;

public class Vehicle {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.vehicle_id
     *
     * @mbg.generated
     */
    private String vehicleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.vehicle_type
     *
     * @mbg.generated
     */
    private String vehicleType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.production_address
     *
     * @mbg.generated
     */
    private String productionAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.route_id
     *
     * @mbg.generated
     */
    private String routeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.production_date
     *
     * @mbg.generated
     */
    private Date productionDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.buy_date
     *
     * @mbg.generated
     */
    private Date buyDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.vehicle_remarks
     *
     * @mbg.generated
     */
    private String vehicleRemarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.vehicle_id
     *
     * @return the value of vehicle.vehicle_id
     *
     * @mbg.generated
     */
    public String getVehicleId() {
        return vehicleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.vehicle_id
     *
     * @param vehicleId the value for vehicle.vehicle_id
     *
     * @mbg.generated
     */
    public void setVehicleId(String vehicleId) {
        this.vehicleId = vehicleId == null ? null : vehicleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.vehicle_type
     *
     * @return the value of vehicle.vehicle_type
     *
     * @mbg.generated
     */
    public String getVehicleType() {
        return vehicleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.vehicle_type
     *
     * @param vehicleType the value for vehicle.vehicle_type
     *
     * @mbg.generated
     */
    public void setVehicleType(String vehicleType) {
        this.vehicleType = vehicleType == null ? null : vehicleType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.production_address
     *
     * @return the value of vehicle.production_address
     *
     * @mbg.generated
     */
    public String getProductionAddress() {
        return productionAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.production_address
     *
     * @param productionAddress the value for vehicle.production_address
     *
     * @mbg.generated
     */
    public void setProductionAddress(String productionAddress) {
        this.productionAddress = productionAddress == null ? null : productionAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.route_id
     *
     * @return the value of vehicle.route_id
     *
     * @mbg.generated
     */
    public String getRouteId() {
        return routeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.route_id
     *
     * @param routeId the value for vehicle.route_id
     *
     * @mbg.generated
     */
    public void setRouteId(String routeId) {
        this.routeId = routeId == null ? null : routeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.production_date
     *
     * @return the value of vehicle.production_date
     *
     * @mbg.generated
     */
    public Date getProductionDate() {
        return productionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.production_date
     *
     * @param productionDate the value for vehicle.production_date
     *
     * @mbg.generated
     */
    public void setProductionDate(Date productionDate) {
        this.productionDate = productionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.buy_date
     *
     * @return the value of vehicle.buy_date
     *
     * @mbg.generated
     */
    public Date getBuyDate() {
        return buyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.buy_date
     *
     * @param buyDate the value for vehicle.buy_date
     *
     * @mbg.generated
     */
    public void setBuyDate(Date buyDate) {
        this.buyDate = buyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.vehicle_remarks
     *
     * @return the value of vehicle.vehicle_remarks
     *
     * @mbg.generated
     */
    public String getVehicleRemarks() {
        return vehicleRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.vehicle_remarks
     *
     * @param vehicleRemarks the value for vehicle.vehicle_remarks
     *
     * @mbg.generated
     */
    public void setVehicleRemarks(String vehicleRemarks) {
        this.vehicleRemarks = vehicleRemarks == null ? null : vehicleRemarks.trim();
    }
}